//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO2020GameShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameCategory
    {
        public long ID { get; set; }
        public long Game { get; set; }
        public long Category { get; set; }
    
        public virtual category category1 { get; set; }
        public virtual game game1 { get; set; }
    }
}
