//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO2020GameShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class regionGame
    {
        public long ID { get; set; }
        public long region { get; set; }
        public long game { get; set; }
        public decimal price { get; set; }
        public Nullable<long> Agelimit { get; set; }
    
        public virtual ageLimit ageLimit1 { get; set; }
        public virtual game game1 { get; set; }
        public virtual Region Region1 { get; set; }
    }
}
